version: '3.8'

services:
  flask:
    build:
      context: ./pythonProject  # Путь к директории с вашим Flask приложением
    ports:
      - "2500:5000"
    depends_on:
      - react


  react:
    build:
      context: ./childout  # Путь к директории с вашим React приложением
    ports:
      - "2501:80"
